#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

eval $(/opt/homebrew/bin/brew shellenv)

# Customize to your needs...
export PATH="$HOME/.poetry/bin:$PATH"
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Projects

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

eval "$(direnv hook zsh)"

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
# can be used in ipython %edit command
export EDITOR=vim
alias wip="git commit -a -n -m 'wip'"
alias ga="git add"

# Load info specific for given workstation
source ~/.zshrc_custom
